export const ErrorCodes = {
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  LOCALBRIDGE_NOT_READY: 'LOCALBRIDGE_NOT_READY',
  TIMEOUT: 'TIMEOUT',
  UPSTREAM_EXECUTION_FAILED: 'UPSTREAM_EXECUTION_FAILED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
